### ISSUE TITLE
local for another lang

### ISSUE THREAD

**Issue by hadijahangiri** [urish/angular2-moment#149]
hi, im use ionic 2 and angular2
 how use angular2-moment for persian lnaguage in app.module

@NgModule({
    declarations: [declarations()
        , LimitLangDirective
        , AndroidButtonDirective
        , TruncatePipe
    ],
    imports: [
        BrowserModule,
        MomentModule ,
        HttpModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [Http]
            }
        }),
      
        IonicStorageModule.forRoot()
    ],
    bootstrap: [IonicApp],
    entryComponents: entryComponents(),
    providers: providers()
})

**Comment by hadijahangiri** [comment]
plz help me

**Comment by truonghoangnguyen** [comment]
I success to change language (ionic 3).
1. do install moment `npm install --save moment`
2. in module do import in NgModule file: 
```
    import { MomentModule } from 'angular2-moment';
    import 'moment/locale/vi';
```

**Comment by Talalaev** [comment]
I use this to change the language in angular 4 application:
```
import * as moment  from 'moment';
moment.locale('ru');
```

**Comment by sebrojas14** [comment]
I'm using it, but amDateFormat doesn't respect locale....

**Comment by alberthoekstra** [comment]
Agree, it doesn't respect that...

**Comment by sebitoelcheater** [comment]
any plans to implement this functionality ?

**Comment by wachri** [comment]
@urish I sent the PR https://github.com/urish/ngx-moment/pull/187 a while ago. Now with the change of the build process the same problem occurs and it could probably solved in a similar way. Tested only locally, but if you move `moment` from the `dependencies` into `devDependencies` it should not install `moment` as own dependency so it uses the global one and you can set the local with in a more natural way with 
```js
import * as moment  from 'moment';
moment.locale('de');
```

We fixed it temporarily with with the `postinstall` in the `package.json`
```
scripts: {
...
    "postinstall": "yarn run fix-moment",
    "fix-moment": "rimraf ./node_modules/ngx-moment/node_modules/moment",

```

Then 
```js
import * as moment  from 'moment';
moment.locale('de');
```
works again

**Comment by urish** [comment]
I think the best solution would be to have moment as a peerDependency, WDYT @wachri ?

**Comment by wachri** [comment]
With the previous version this hasn't worked, but now this should be the solution :).

**Comment by urish** [comment]
released as 3.0.0

**Comment by thienedits** [comment]
@urish  Locale still not working properly in 3.1.0. Doesn't seem to change until the next change detection.
